### PR TITLE
Switch lib/pq import to pf-qiu/pq for varbit type fix

### PR DESCRIPTION
**Pull request by pf-qiu**
lib/pq doesn't support bit and varbit type. We can't query length
of bit and varbit type via original library. We have created a PR
in upstream repo, hope they can merge it soon. In the mean time,
we switch to our custom fixed version. Then this commit can be
reverted after fix is merged into upstream.

### CODE REVIEW

**Comment by yydzero** [comment]
How about put pq under greenplum-db org, instead of personal repo?

**Comment by adam8157** [comment]
https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#source

> A source rule can specify an alternate location from which the name'd project should be retrieved. It is primarily useful for temporarily specifying a fork for a repository.

**Comment by chrishajas** [comment]
I'm apprehensive to include forks since they can become burdonsome to maintain and keep up to date, especially if the change doesn't get merged in upstream for some reason.

How are you planning to use this? If you're querying a table that has a bit or varbit type, would casting it to text such as `select varbit_col::text` be a workaround?

**Comment by pf-qiu** [comment]
We have worked out a workaround to query catalog directly instead of rely on the wire protocol. Closing this PR.
If we encounter similar issues, I'm +1 on yydzero's approach, to create a forked version in greenplum organization.

**Pull request closed without merging**
