### PR TITLE
New a DB connection with database, username, host and port

### PR DESCRIPTION
**Pull request by adam8157**
New a DB connection with detailed arguments, so we could connect to
different clusters, the former one is name "NewDBConnFromEnvironment"
now.

### CODE REVIEW

**Comment by adam8157** [comment]
We have the feature request to connect multiple clusters, better to support it in common libs I suppose.

**Comment by chrishajas** [comment]
Looks good. I'd also be in favor of instead changing NewDBConn to take 4 arguments (dbname, user, host port) and creating a new wrapper function (for example, NewDefaultDBConn) that only takes the dbname as an argument. That would require current applications to update their code, but it would also give us compile-time type checking.

**Comment by cjcjameson** [comment]
+1 probably best to keep the argument types rather specific and have a
separate constructor.

**Comment by jmcatamney** [comment]
+1 to having a type-checked constructor.  I'd name the wrapper constructor something more specific like NewDBConnFromEnvironment, as the actual logic in it is around environment variables and "DefaultDBConn" can imply a connection created with just the defaults of template1/gpadmin/mdw/5432.

**Comment by adam8157** [comment]
Thanks for reviewing, type checking makes sense, will have another version.

**Comment by adam8157** [comment]
Updated, please help reviewing.

I decided to pick a new name and keep the compatibility, and not having the default values in case accidentally connecting to other databases.

**Review by chrishajas — APPROVED** [review]
Logic looks good to me. I don't mind having to change function names if they're more explicit/better names since we version this dependency and can simply update the names once we bump the version. I agree with Jamie that calling the constructor "NewDBConnFromEnvironment" would be a more accurate name than "NewDBConn" or "NewDefaultDBConn".

**Comment by adam8157** [comment]
I agree :) Update to the better names and merge.

**Pull request merged**
